sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -U -r test-requirements.txt
  - pip install codecov

# command to run tests
script: python check.py -C

after_success:
  - codecov
